print("python is running")
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import pickle



emails = [
    "Congratulations! You won a lottery worth $1,000,000.",
    "Claim your free gift now.",
    "You have won a cash prize. Click here.",
    "Limited time offer! Buy now and save 80%.",
    "Get rich quickly with this secret method.",
    "Your account has been selected for a reward.",
    "Urgent! Verify your bank details immediately.",
    "Earn money from home without any investment.",
    "Exclusive deal just for you. Click now.",
    "You are the lucky winner of an iPhone.",
    "Free vacation package waiting for you.",
    "Congratulations! Your number has been selected.",
    "Win a brand new car today.",
    "Click here to claim your reward.",
    "Act now before this offer expires.",
    "You have been pre-approved for a loan.",
    "Get instant access to premium content.",
    "Double your income in just one week.",
    "Special discount available only today.",
    "Your account will be suspended. Verify now.",
    "Free entry into our prize draw.",
    "Lowest prices guaranteed. Shop now.",
    "You have received a gift voucher.",
    "Unlock secret investment opportunities.",
    "Earn $500 daily from home.",
    "Claim your cashback reward today.",
    "You have an unclaimed refund waiting.",
    "Hot deals on electronics. Buy now.",
    "Exclusive membership offer just for you.",
    "Congratulations! You are our grand prize winner.",
    "This is your final warning.",
    "Limited stock available. Order now.",
    "You have been selected for a free trial.",
    "Get free access to premium services.",
    "Your payment information needs verification.",
    "Win big with our online contest.",
    "Receive free coupons instantly.",
    "Earn passive income effortlessly.",
    "Special promotion ending soon.",
    "Get a free smartphone today.",
    "You are eligible for a cash reward.",
    "Instant approval for your credit application.",
    "Exclusive online earning opportunity.",
    "Claim your bonus before midnight.",
    "Click here to receive your prize.",
    "Your account has won a reward.",
    "Free shopping voucher available now.",
    "Earn thousands every month from home.",
    "Lucky draw winner announcement.",
    "Claim your free movie tickets.",
    "You have been chosen for a special offer.",
    "Investment opportunity with guaranteed returns.",
    "Get free gift cards instantly.",
    "Urgent action required on your account.",
    "Win exciting prizes every day.",
    "Congratulations! You are a selected winner.",
    "Exclusive reward waiting for you.",
    "Take advantage of this amazing deal.",
    "Free membership for a limited time.",
    "Claim your reward before it expires.",
    "Your PayPal account needs immediate verification.",
    "Congratulations! You have won a free laptop.",
    "Earn money online with no experience needed.",
    "Exclusive crypto investment opportunity.",
    "Claim your Amazon gift card now.",
    "You are our lucky customer today.",
    "Get a free Netflix subscription.",
    "Special reward waiting in your account.",
    "Verify your account to avoid suspension.",
    "Win a luxury holiday package.",
    "Limited offer: 90 percent discount available.",
    "Get approved for a loan instantly.",
    "Claim your free shopping voucher.",
    "Your account has been compromised. Click here.",
    "Exclusive bonus available for a short time.",
    "You have won free airline tickets.",
    "Act now to receive your reward.",
    "Earn extra cash from your smartphone.",
    "Free premium membership available.",
    "Unlock hidden profits today.",
    "Congratulations! You qualify for a free gift.",
    "Claim your exclusive cashback offer.",
    "Win a gaming console today.",
    "Free recharge available now.",
    "Receive a reward for completing a survey.",
    "Click now to secure your prize.",
    "Exclusive giveaway for selected users.",
    "You have won a shopping spree.",
    "Special promotion just launched.",
    "Free access to VIP content.",
    "Earn income while you sleep.",
    "Claim your complimentary gift package.",
    "Limited-time financial opportunity.",
    "You are selected for a secret reward.",
    "Your refund is ready to claim.",
    "Win guaranteed prizes today.",
    "Exclusive membership benefits unlocked.",
    "Get your free trial immediately.",
    "Special offer for loyal customers.",
    "Earn money with zero investment.",
    "You have won a luxury watch.",
    "Receive free bitcoins instantly.",
    "Unlock your reward before it expires.",
    "You have a pending cash reward.",
    "Win a free shopping voucher.",
    "Exclusive discount code inside.",
    "Claim your free hotel stay.",
    "Limited seats available. Register now.",
    "Free insurance quote available.",
    "Earn rewards by clicking here.",
    "Special cashback offer ends tonight.",
    "Your account requires urgent action.",
    "You have been selected as a winner.",
    "Win prizes with one simple click.",
    "Exclusive opportunity for fast earnings.",
    "Get free coupons worth $100.",
    "Claim your reward without delay.",
    "Congratulations! Your application was approved.",
    "Limited period bonus available now.",
    "Earn easy money from home.",
    "Your prize is waiting to be collected.",
    "Exclusive invitation to claim rewards.",
    "Receive free products every month.",
    "Claim your luxury vacation package.",
    "Special deal only for selected users.",
    "You are entitled to a free reward.",
    "Win cash instantly today.",
    "Get your free eBook now.",
    "Limited-time access to premium features.",
    "Exclusive offer on branded products.",
    "Claim your lucky draw prize.",
    "Receive guaranteed cashback today.",
    "Urgent notice regarding your account.",
    "You have won a free tablet.",
    "Earn daily income with simple tasks.",
    "Claim your gift voucher immediately.",
    "Special online deal expires soon.",
    "Free consultation available today.",
    "Congratulations! Your reward is ready.",
    "Exclusive rewards program invitation.",
    "Win a smartphone with one click.",
    "Get access to secret discounts.",
    "Claim your free merchandise now.",
    "Receive rewards for referrals.",
    "Limited-time prize redemption available.",
    "Exclusive chance to win big.",
    "Earn extra income every week.",
    "You have been selected for a giveaway.",
    "Claim your bonus reward today.",
    "Free subscription activated for you.",
    "Special invitation to VIP members.",
    "Congratulations! You are today's winner.",
    "Receive your prize before midnight.",
    "Exclusive savings available now.",
    "Win amazing rewards instantly.",
    "Claim your free reward package."
]



labels = [1, 1, 1, 0, 0, 0, 0, 1]



vectorizer = CountVectorizer()
X = vectorizer.fit_transform(emails)



model = MultinomialNB()
model.fit(X, labels)



pickle.dump(model, open("spam_model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))

print("Model Trained Successfully")